FROM node:20-alpine AS builder
WORKDIR /app

COPY pixelrun-site/pixelrun-react/package.json ./
COPY pixelrun-site/pixelrun-react/package-lock.json* ./

RUN npm install

COPY pixelrun-site/pixelrun-react/. ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
